### ISSUE TITLE
Hi bạn, mình muốn trao đổi chút về bản Hackintosh này cho 5501

### ISSUE THREAD

**Issue by HenryNguyenHCMVN** [Zenfection/hackintosh_dell_latitude_5501#1]
Bản này hiện tại bạn đang cài cho bản nào vậy?

Bạn fix được full lỗi cho máy chưa? Mình fix mãi không được, share ra màn hình thứ 2 cũng không được.

**Comment by zenkiet** [comment]
Đã fix full
